defmodule BbhWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :bbh

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_bbh_key",
    signing_salt: "U9SoZHlh",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, :x_headers, session: @session_options]],
    longpoll: [connect_info: [:peer_data, :x_headers, session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :bbh,
    gzip: not code_reloading?,
    only: BbhWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :bbh
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId

  # Phoenix's request logger reads this :log option from the telemetry metadata.
  # log_level/1 keeps the frequent /health probes at :debug (hidden at the
  # default :info) while everything else logs at :info. See log_level/1 below.
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint], log: {__MODULE__, :log_level, []}

  # Health probes for the container/reverse-proxy — mounted before the router
  # so they skip session/parsing and stay cheap.
  plug BbhWeb.Plugs.Health

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug BbhWeb.Router

  # Per-request log level for Phoenix's request logger (wired via Plug.Telemetry
  # above). Container/proxy health probes hit /health/* every few seconds; logging
  # them at :debug keeps them out of prod logs (default :info) while still visible
  # when LOG_LEVEL=debug. Every other request logs at :info.
  @doc false
  def log_level(%Plug.Conn{request_path: "/health/" <> _}), do: :debug
  def log_level(_conn), do: :info
end
